PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS cards(code TEXT PRIMARY KEY, type TEXT NOT NULL, duration_seconds INTEGER NOT NULL, status TEXT NOT NULL DEFAULT 'unused', activated_at INTEGER, expires_at INTEGER, grace_until INTEGER, deleted_at INTEGER, world_id TEXT, created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS worlds(id TEXT PRIMARY KEY, card_code TEXT UNIQUE NOT NULL, genre TEXT NOT NULL, relation_type TEXT NOT NULL, plot_type TEXT NOT NULL, title TEXT NOT NULL, background TEXT NOT NULL, rules_json TEXT NOT NULL, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS worldbooks(world_id TEXT PRIMARY KEY, data_json TEXT NOT NULL, updated_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS characters(id TEXT PRIMARY KEY, world_id TEXT NOT NULL, name TEXT NOT NULL, sex TEXT, age INTEGER, identity TEXT, faction TEXT, personality TEXT, background TEXT, past TEXT, goals TEXT, initial_attitude TEXT, affinity INTEGER NOT NULL DEFAULT 0, encountered INTEGER NOT NULL DEFAULT 0, contact INTEGER NOT NULL DEFAULT 0, arc TEXT, secrets_json TEXT, clue_rules_json TEXT, encounter_rules_json TEXT, chat_rules TEXT);
CREATE TABLE IF NOT EXISTS relationships(id TEXT PRIMARY KEY, world_id TEXT NOT NULL, a_id TEXT NOT NULL, b_id TEXT NOT NULL, relation TEXT NOT NULL, strength INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS events(id TEXT PRIMARY KEY, world_id TEXT NOT NULL, stage INTEGER NOT NULL DEFAULT 0, title TEXT NOT NULL, body TEXT NOT NULL, trigger_json TEXT NOT NULL, fired INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS clues(id TEXT PRIMARY KEY, world_id TEXT NOT NULL, character_id TEXT, title TEXT NOT NULL, content TEXT NOT NULL, unlock_json TEXT NOT NULL, unlocked INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS messages(id INTEGER PRIMARY KEY AUTOINCREMENT, world_id TEXT NOT NULL, character_id TEXT, channel TEXT NOT NULL, role TEXT NOT NULL, content TEXT NOT NULL, created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS player_settings(world_id TEXT PRIMARY KEY, data_json TEXT NOT NULL, updated_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS seeds(id TEXT PRIMARY KEY, category TEXT NOT NULL, name TEXT NOT NULL, data_json TEXT NOT NULL, enabled INTEGER NOT NULL DEFAULT 1, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS admin_settings(k TEXT PRIMARY KEY, v TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS admin_sessions(token TEXT PRIMARY KEY, expires_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS idx_cards_status ON cards(status);
CREATE INDEX IF NOT EXISTS idx_characters_world ON characters(world_id);
CREATE INDEX IF NOT EXISTS idx_messages_world ON messages(world_id);
