const TYPES={"1h":3600,"5h":18000,"12h":43200,"1d":86400,"7d":604800,"15d":1296000,"30d":2592000};
const now=()=>Math.floor(Date.now()/1000); const id=()=>crypto.randomUUID();
const json=(d,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{"content-type":"application/json","access-control-allow-origin":"*","access-control-allow-headers":"content-type,authorization"}});
async function q(env,sql,...p){return env.DB.prepare(sql).bind(...p).all()} async function one(env,sql,...p){return env.DB.prepare(sql).bind(...p).first()} async function run(env,sql,...p){return env.DB.prepare(sql).bind(...p).run()}
function pick(a){return a[Math.floor(Math.random()*a.length)]}
const genres=[['xianxia','修真世界','灵脉、宗门与秘境交织的修真大陆。'],['wuxia','江湖世界','门派、侠客、恩怨与江湖势力并存。'],['urban','现代都市','现代城市中隐藏着各自秘密的人际网络。'],['fantasy','奇幻大陆','王国、魔法、种族与古老遗迹组成的大陆。'],['scifi','星际时代','星舰、殖民地、人工智能与未知文明。'],['apocalypse','末日世界','灾变后的聚居地与资源争夺。'],['cthulhu','深海迷雾','调查者面对无法轻易理解的未知。'],['beastfolk','兽人世界','不同族群在城市与荒野间共存。']];
const relations=['BG','BL','GL','无固定关系','师徒','宿敌','青梅竹马']; const plots=['阴谋','复仇','探秘','冒险','成长','慢热','群像'];
const names=['凌朔然','沈砚','顾清辞','谢临川','苏晚','陆沉','叶知秋','温予安','裴昭','秦川'];
async function seedDefaults(env){if((await one(env,'SELECT COUNT(*) c FROM seeds')).c) return; const t=now(); for(const [category,name,data] of [['world','xianxia','修真世界'],['world','urban','现代都市'],['world','fantasy','奇幻大陆'],['relation','BG','BG'],['relation','BL','BL'],['relation','GL','GL'],['plot','阴谋','阴谋'],['plot','探秘','探秘'],['plot','成长','成长']]) await run(env,'INSERT INTO seeds VALUES(?,?,?,?,1,?,?)',id(),category,name,JSON.stringify({label:data}),t,t)}
function auth(req){return (req.headers.get('authorization')||'').replace(/^Bearer /,'')}
async function admin(env,req){const t=auth(req); return t && await one(env,'SELECT token FROM admin_sessions WHERE token=? AND expires_at>?',t,now())}
async function createWorld(env,code){const g=pick(genres), r=pick(relations), p=pick(plots), wid=id(), title=`${pick(['序章','未名','长夜','星火','迷城'])}·${g[1]}`; const bg=`这是一个${g[1]}。${g[2]} 当前主线围绕“${p}”展开，世界关系为${r}。剧情会根据你的行动继续发展。`; const rules={genre:g[0],power:g[0]==='xianxia'?'境界与宗门体系':'世界内规则',relation:r,plot:p}; await run(env,'INSERT INTO worlds VALUES(?,?,?,?,?,?,?,?,?,?)',wid,code,g[0],r,p,title,bg,JSON.stringify(rules),now(),now()); await run(env,'INSERT INTO worldbooks VALUES(?,?,?)',wid,JSON.stringify({background:bg,rules,location:'初始区域',time:'第一日',weather:'未知',factions:[],knownCharacters:[]}),now());
 for(let i=0;i<10;i++){const cid=id(); const n=i===0?names[0]:names[(i+1)%names.length]; const aff=i===0?35:0; await run(env,'INSERT INTO characters VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',cid,wid,n,i%2?'女':'男',20+i,`关键角色${i+1}`,`${i%2?'势力B':'势力A'}`,`谨慎、克制，行动受个人目标影响。`,`与${g[1]}背景相关的过去。`,`隐藏目标${i+1}`,`寻找真相`,`复杂`,`${aff}`,0,aff>=30?1:0,`成长线${i+1}`,JSON.stringify([{title:'隐藏秘密',content:'需要满足条件后解锁'}]),JSON.stringify({affinity:60,event:'special'}),JSON.stringify({location:'剧情区域'}),'基于已发生剧情交流。'); }
 const cs=await q(env,'SELECT id,name FROM characters WHERE world_id=?',wid); for(let i=0;i<cs.results.length-1;i++) await run(env,'INSERT INTO relationships VALUES(?,?,?,?,?,?)',id(),wid,cs.results[i].id,cs.results[i+1].id, i%2?'同伴':'竞争',20);
 await run(env,'INSERT INTO events VALUES(?,?,?,?,?,?,0)',id(),wid,0,'初遇','你来到世界的起点。',JSON.stringify({stage:0})); await run(env,'INSERT INTO events VALUES(?,?,?,?,?,?,0)',id(),wid,1,'暗线','一个尚未解释的线索出现。',JSON.stringify({stage:1})); await run(env,'INSERT INTO player_settings VALUES(?,?,?)',wid,JSON.stringify({theme:'system',autoVoice:false,plotPreference:'balanced'}),now()); return wid}
async function cleanup(env){const t=now(); const rows=await q(env,'SELECT * FROM cards WHERE status="active" AND expires_at<?',t); for(const c of rows.results){if(c.grace_until && c.grace_until>t) continue; if(c.expires_at+t*0===c.expires_at){const grace=c.expires_at+5*86400;if(t<grace){await run(env,'UPDATE cards SET grace_until=? WHERE code=?',grace,c.code); continue} await run(env,'DELETE FROM worlds WHERE id=?',c.world_id); await run(env,'DELETE FROM cards WHERE code=?',c.code)}}}
async function route(req,env){await seedDefaults(env); const u=new URL(req.url), p=u.pathname; if(req.method==='OPTIONS')return new Response('',{headers:{'access-control-allow-origin':'*','access-control-allow-headers':'content-type,authorization','access-control-allow-methods':'GET,POST,DELETE,OPTIONS'}}); if(p==='/api/auth/card'&&req.method==='POST'){const {code}=await req.json(); const secret=await one(env,'SELECT v FROM admin_settings WHERE k="admin_password"'); if(secret?.v===code){const token=id();await run(env,'INSERT INTO admin_sessions VALUES(?,?,)',token,now()+86400).catch(()=>{}); return json({admin:true,token})} const c=await one(env,'SELECT * FROM cards WHERE code=?',code); if(!c)return json({error:'卡密无效'},401); if(c.status==='revoked')return json({error:'卡密已冻结'},403); if(c.status==='unused'){const wid=await createWorld(env,code);const t=now(),dur=c.duration_seconds;await run(env,'UPDATE cards SET status="active",activated_at=?,expires_at=?,grace_until=?,world_id=? WHERE code=?',t,t+dur,t+dur+5*86400,wid,code);return json({worldId:wid})} if(c.status==='active'){if(c.expires_at<now())return json({error:'已过期，请续期'},403);return json({worldId:c.world_id})} return json({error:'卡密不可用'},403)}
 if(p==='/api/world'&&req.method==='GET'){const wid=u.searchParams.get('id');const w=await one(env,'SELECT * FROM worlds WHERE id=?',wid);if(!w)return json({error:'世界不存在'},404);const chars=await q(env,'SELECT id,name,sex,age,identity,faction,personality,affinity,encountered,contact,arc FROM characters WHERE world_id=?',wid);const wb=await one(env,'SELECT data_json FROM worldbooks WHERE world_id=?',wid);return json({world:w,characters:chars.results,worldbook:JSON.parse(wb.data_json)})}
 if(p==='/api/story/message'&&req.method==='POST'){const {worldId,content}=await req.json();const w=await one(env,'SELECT * FROM worlds WHERE id=?',worldId);if(!w)return json({error:'世界不存在'},404);await run(env,'INSERT INTO messages(world_id,channel,role,content,created_at) VALUES(?,?,?,?,?)',worldId,'story','user',content,now());let reply=`【${w.title}】\n${pick(['风声掠过，你的行动改变了局势。','远处传来动静，新的线索正在形成。','眼前的人注意到了你，但没有立即表露态度。'])}`; const cs=await q(env,'SELECT id,name,affinity,encountered,contact FROM characters WHERE world_id=?',worldId); if(content.includes('凌朔然')){const c=cs.results.find(x=>x.name==='凌朔然');if(c){await run(env,'UPDATE characters SET encountered=1,affinity=CASE WHEN affinity<30 THEN affinity+5 ELSE affinity+1 END,contact=CASE WHEN affinity+1>=30 THEN 1 ELSE contact END WHERE id=?',c.id);reply+='\n你真正遇见了凌朔然。'}} await run(env,'INSERT INTO messages(world_id,channel,role,content,created_at) VALUES(?,?,?,?,?)',worldId,'story','assistant',reply,now());return json({reply})}
 if(p==='/api/contacts'&&req.method==='GET'){const wid=u.searchParams.get('worldId');const cs=await q(env,'SELECT id,name,sex,age,identity,faction,personality,affinity,encountered,contact FROM characters WHERE world_id=? AND contact=1 AND affinity>=30',wid);return json({contacts:cs.results})}
 if(p==='/api/contact/message'&&req.method==='POST'){const {worldId,characterId,content}=await req.json();const c=await one(env,'SELECT * FROM characters WHERE id=? AND world_id=?',characterId,worldId);if(!c||!c.contact||c.affinity<30)return json({error:'该角色尚未成为联系人'},403);await run(env,'INSERT INTO messages(world_id,character_id,channel,role,content,created_at) VALUES(?,?,?,?,?,?)',worldId,characterId,'contact','user',content,now());const reply=`${c.name}看完你的消息，沉默片刻后回复：“我会记住。”`;await run(env,'INSERT INTO messages(world_id,character_id,channel,role,content,created_at) VALUES(?,?,?,?,?,?)',worldId,characterId,'contact','assistant',reply,now());return json({reply})}
 if(p==='/api/worldbook'&&req.method==='GET'){const wb=await one(env,'SELECT data_json FROM worldbooks WHERE world_id=?',u.searchParams.get('worldId'));return json(wb?JSON.parse(wb.data_json):{})}
 if(p==='/api/settings'&&req.method==='GET'){const s=await one(env,'SELECT data_json FROM player_settings WHERE world_id=?',u.searchParams.get('worldId'));return json(s?JSON.parse(s.data_json):{})} if(p==='/api/settings'&&req.method==='POST'){const {worldId,data}=await req.json();await run(env,'INSERT INTO player_settings(world_id,data_json,updated_at) VALUES(?,?,?) ON CONFLICT(world_id) DO UPDATE SET data_json=excluded.data_json,updated_at=excluded.updated_at',worldId,JSON.stringify(data),now());return json({ok:true})}
 if(p.startsWith('/api/admin/')&&!await admin(env,req))return json({error:'管理员未授权'},401);
 if(p==='/api/admin/cards'&&req.method==='GET'){const r=await q(env,'SELECT code,type,status,activated_at,expires_at,grace_until,world_id,created_at FROM cards ORDER BY created_at DESC');return json(r.results)}
 if(p==='/api/admin/cards'&&req.method==='POST'){const {type,count=1}=await req.json();if(!TYPES[type])return json({error:'无效卡类型'},400);const out=[];for(let i=0;i<Math.min(count,500);i++){let code;do{code=Math.random().toString(36).slice(2,8).toUpperCase()+Math.random().toString(36).slice(2,6).toUpperCase()}while(await one(env,'SELECT code FROM cards WHERE code=?',code));await run(env,'INSERT INTO cards VALUES(?,?,?,?,?,?,?,?,?,?)',code,type,TYPES[type],'unused',null,null,null,null,null,now());out.push(code)}return json({cards:out})}
 if(p==='/api/admin/renew'&&req.method==='POST'){const {code}=await req.json();const c=await one(env,'SELECT * FROM cards WHERE code=?',code);if(!c||c.status==='revoked')return json({error:'卡密不可续期'},400);const base=Math.max(now(),c.expires_at||now());const exp=base+c.duration_seconds;await run(env,'UPDATE cards SET status="active",expires_at=?,grace_until=?,deleted_at=NULL WHERE code=?',exp,exp+5*86400,code);return json({expiresAt:exp})}
 if(p==='/api/admin/freeze'&&req.method==='POST'){const {code}=await req.json();await run(env,'UPDATE cards SET status="revoked" WHERE code=?',code);return json({ok:true})}
 if(p==='/api/admin/worlds'&&req.method==='GET'){const r=await q(env,'SELECT * FROM worlds ORDER BY created_at DESC');return json(r.results)}
 if(p==='/api/admin/worlds'&&req.method==='DELETE'){const wid=u.searchParams.get('id');await run(env,'DELETE FROM worlds WHERE id=?',wid);return json({ok:true})}
 if(p==='/api/admin/seeds'&&req.method==='GET'){const r=await q(env,'SELECT * FROM seeds ORDER BY category,name');return json(r.results)}
 if(p==='/api/admin/seeds'&&req.method==='POST'){const {category,name,data}=await req.json();const t=now();await run(env,'INSERT INTO seeds VALUES(?,?,?,?,1,?,?)',id(),category,name,JSON.stringify(data||{}),t,t);return json({ok:true})}
 if(p==='/api/admin/password'&&req.method==='POST'){const {password}=await req.json();if(!password||password.length<8)return json({error:'密码至少8位'},400);await run(env,'INSERT INTO admin_settings(k,v) VALUES("admin_password",?) ON CONFLICT(k) DO UPDATE SET v=excluded.v',password);return json({ok:true})}
 return json({error:'Not Found'},404)}
export default {async fetch(req,env){try{return await route(req,env)}catch(e){return json({error:e.message},500)}},async scheduled(_e,env){await cleanup(env)}};
